// GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
// Re-run the script when new photography lands in `Vishal Photos/`.

export type Photo = {
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const photos = {
  "fleet-tata-dusk": {
    src: "/photos/fleet-tata-dusk.jpg",
    alt: "Two Vishal Transport staff buses in TATA Electronics livery parked nose to nose at dusk.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAhEAACAgICAQUAAAAAAAAAAAABAgMRACEEEhMFFDFRgf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwChPXJSoEqLK9DVdd5FzeZLy4zGyeNlPwNX+4nso2mLdnFiiAdViLwIRJ5LctVba9fWIX//2Q==",
  },
  "fleet-new-staff-buses": {
    src: "/photos/fleet-new-staff-buses.jpg",
    alt: "Two newly delivered Vishal Transport staff buses parked side by side at the operations yard.",
    width: 1280,
    height: 720,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAIRAAAwABAQkAAAAAAAAAAAAAAQIDAHIEERITIjQ1kcH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEDEf/aAAwDAQACEQMRAD8AOdriQVKRVeEkAnq9ZRrtJmw5kGAUkDd8xrd2moZkbyk9ZwlViOeH/9k=",
  },
  "fleet-row-marcopolo": {
    src: "/photos/fleet-row-marcopolo.jpg",
    alt: "Five new Vishal Transport staff buses lined up in a row at the yard under an open sky.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAIxAAAQMDAgcAAAAAAAAAAAAAAQIDEQAEMSFhBRIUIjJBUf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAVEQEBAAAAAAAAAAAAAAAAAAAAE//aAAwDAQACEQMRAD8AVL7BKOZ5GJk+tq3scRtW+0OpnXT5QdLbr8mEGdqkWdsFBQZSDM5OaVJv/9k=",
  },
  "client-uno-minda": {
    src: "/photos/client-uno-minda.jpg",
    alt: "Vishal Transport and UNO MINDA staff standing in front of two staff buses at the UNO MINDA plant.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAE/8QAHhAAAwACAwADAAAAAAAAAAAAAQIDABEEBSExUYH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAS/9oADAMBAAIRAxEAPwC4/Z6cO6LM7+B55+5vn2C1NBOZOgSDve8a8JWfdZI5A8LLvCnxoyJaUlQ/ajG0w//Z",
  },
  "client-tata-electronics": {
    src: "/photos/client-tata-electronics.jpg",
    alt: "Three Vishal Transport buses in TATA Electronics livery with their drivers and crew.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBf/EACAQAQEAAQQBBQAAAAAAAAAAAAECAAMFESESIzFBkaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQASE//aAAwDAQACEQMRAD8Are+atwehEL0qvX5iRu9TB5xGqqgzWbj8HHWAmefY+seiRgv/2Q==",
  },
  "client-jbm-ogihara": {
    src: "/photos/client-jbm-ogihara.jpg",
    alt: "Vishal Transport drivers and support crew assembled in front of six vehicles at the JBM Ogihara Automotive plant.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAgT/xAAiEAABAwQABwAAAAAAAAAAAAABAgMRAAQSIQUTMUFhcaH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/EABgRAAIDAAAAAAAAAAAAAAAAAAABERJR/9oADAMBAAIRAxEAPwCLnItb5C3luKdRBISCZMeqvc440s45vNQInf3VLIhzyep7mk6okHIBWp2JqbLBB//Z",
  },
  "client-teal": {
    src: "/photos/client-teal.jpg",
    alt: "Vishal Transport office staff, managers and drivers assembled in front of four vehicles at a client site.",
    width: 1280,
    height: 853,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAHxAAAgICAgMBAAAAAAAAAAAAAQMCEQAEEiETIkEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAYEQACAwAAAAAAAAAAAAAAAAAAAQITFP/aAAwDAQACEQMRAD8Abrv12pgyUvHyANSzWbNeMLLYVfHo/cUvV142YoXZ/fUd5TrIBsJWCPoiAcpokClH/9k=",
  },
  "workforce-uno-minda": {
    src: "/photos/workforce-uno-minda.jpg",
    alt: "Uniformed Vishal Transport staff standing together beside a staff bus at the UNO MINDA plant.",
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBf/EACEQAAICAgAHAQAAAAAAAAAAAAECAxEABAUhMTIzcZKh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAREx/9oADAMBAAIRAxEAPwCOHZaHZjkdlRBz7hf7m0OLQbDKFcB+lXeOXQ1YnYrAhYmyzCyT7OB9eG/EnyMmrBh//9k=",
  },
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
