/**
 * One-off authoring step: takes the raw supplied photography out of
 * `Vishal Photos/`, strips camera metadata, re-encodes it for the web, and
 * emits the typed manifest that `src/lib/photos.ts` re-exports.
 *
 * Sources are 1280px phone/camera originals — deliberately never upscaled.
 * Run with `node scripts/optimize-photos.mjs` when new photography lands.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC_DIR = "Vishal Photos";
const OUT_DIR = "public/photos";
const MAX_WIDTH = 1280;
const QUALITY = 82;

/** slug ← source file. Alt text is written for screen readers, not SEO stuffing. */
const PHOTOS = [
  {
    slug: "fleet-tata-dusk",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (9).jpeg",
    alt: "Two Vishal Transport staff buses in TATA Electronics livery parked nose to nose at dusk.",
  },
  {
    slug: "fleet-new-staff-buses",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (1).jpeg",
    alt: "Two newly delivered Vishal Transport staff buses parked side by side at the operations yard.",
  },
  {
    slug: "fleet-row-marcopolo",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (10).jpeg",
    alt: "Five new Vishal Transport staff buses lined up in a row at the yard under an open sky.",
  },
  {
    slug: "client-uno-minda",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (3).jpeg",
    alt: "Vishal Transport and UNO MINDA staff standing in front of two staff buses at the UNO MINDA plant.",
  },
  {
    slug: "client-tata-electronics",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (6).jpeg",
    alt: "Three Vishal Transport buses in TATA Electronics livery with their drivers and crew.",
  },
  {
    slug: "client-jbm-ogihara",
    src: "WhatsApp Image 2026-08-15 at 16.17.02.jpeg",
    alt: "Vishal Transport drivers and support crew assembled in front of six vehicles at the JBM Ogihara Automotive plant.",
  },
  {
    slug: "client-teal",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (8).jpeg",
    alt: "Vishal Transport office staff, managers and drivers assembled in front of four vehicles at a client site.",
  },
  {
    slug: "workforce-uno-minda",
    src: "WhatsApp Image 2026-08-15 at 16.17.02 (2).jpeg",
    alt: "Uniformed Vishal Transport staff standing together beside a staff bus at the UNO MINDA plant.",
  },
];

await mkdir(OUT_DIR, { recursive: true });

const manifest = [];

for (const photo of PHOTOS) {
  const input = path.join(SRC_DIR, photo.src);
  const outFile = `${photo.slug}.jpg`;

  // sharp drops EXIF/GPS by default — no withMetadata() call, deliberately.
  const pipeline = sharp(input).rotate().resize({
    width: MAX_WIDTH,
    withoutEnlargement: true,
  });

  const { width, height } = await pipeline
    .clone()
    .jpeg({ quality: QUALITY, mozjpeg: true })
    .toFile(path.join(OUT_DIR, outFile));

  // 16px-wide blur seed, inlined as a data URI so the placeholder costs
  // no extra request.
  const blur = await sharp(input)
    .rotate()
    .resize({ width: 16 })
    .jpeg({ quality: 40 })
    .toBuffer();

  manifest.push({
    slug: photo.slug,
    src: `/photos/${outFile}`,
    alt: photo.alt,
    width,
    height,
    blurDataURL: `data:image/jpeg;base64,${blur.toString("base64")}`,
  });

  console.log(`${photo.src}\n  → ${outFile}  ${width}×${height}`);
}

const body = `// GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
// Re-run the script when new photography lands in \`Vishal Photos/\`.

export type Photo = {
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const photos = {
${manifest
  .map(
    (p) => `  "${p.slug}": {
    src: "${p.src}",
    alt: ${JSON.stringify(p.alt)},
    width: ${p.width},
    height: ${p.height},
    blurDataURL:
      "${p.blurDataURL}",
  },`,
  )
  .join("\n")}
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
`;

await writeFile("src/lib/photos.ts", body);
console.log(`\n${manifest.length} photos → ${OUT_DIR}, manifest → src/lib/photos.ts`);
