import Image from "next/image";

/**
 * The official brand mark. Assets are generated by `scripts/build-logo.mjs`
 * from the supplied lockup — see that file for the colour-flattening rationale.
 *
 * `mono` is the white knockout, for navy/dark surfaces where the navy emblem
 * would otherwise disappear. `emblem` is the reduced "V" icon for square or
 * very small slots — the full lockup's tagline turns illegible below ~30px.
 */
const ASSETS = {
  full: { src: "/brand/vishal-logo.png", width: 2083, height: 535 },
  mono: { src: "/brand/vishal-logo-mono.png", width: 2083, height: 535 },
  emblem: { src: "/brand/vishal-logo-emblem.png", width: 617, height: 536 },
  emblemMono: { src: "/brand/vishal-logo-mono-emblem.png", width: 617, height: 536 },
} as const;

type LogoProps = {
  variant?: keyof typeof ASSETS;
  /** Rendered height in CSS px — drives the reserved box, so there is no CLS. */
  height: number;
  className?: string;
  priority?: boolean;
  /**
   * Accessible name. Pass "" when an ancestor (e.g. an aria-labelled link, or
   * a paired visible wordmark) already names the mark, to avoid a double read.
   */
  alt?: string;
};

export function Logo({
  variant = "full",
  height,
  className = "",
  priority = false,
  alt = "",
}: LogoProps) {
  const asset = ASSETS[variant];
  const width = Math.round((asset.width / asset.height) * height);

  return (
    <Image
      src={asset.src}
      alt={alt}
      width={width}
      height={height}
      sizes={`${width}px`}
      priority={priority}
      aria-hidden={alt === "" ? true : undefined}
      className={className}
    />
  );
}
