import Image from "next/image";

/**
 * The official brand mark. Assets are generated by `scripts/build-logo.mjs`
 * from the supplied lockup — see that file for the colour-flattening rationale.
 *
 * `mono` is the white knockout, for navy/dark surfaces where the navy emblem
 * would otherwise disappear.
 */
const ASSETS = {
  full: { src: "/brand/vishal-logo.png", width: 780, height: 200 },
  mono: { src: "/brand/vishal-logo-mono.png", width: 780, height: 200 },
} as const;

type LogoProps = {
  variant?: keyof typeof ASSETS;
  /** Intrinsic height in CSS px — reserves the box, so there is no CLS. */
  height: number;
  /**
   * Responsive `sizes` describing the width the mark is ACTUALLY painted at.
   *
   * This must be passed whenever CSS overrides the intrinsic size. Deriving it
   * from `height` (the old behaviour) made the browser fetch for the intrinsic
   * box rather than the rendered one — the About plate asked for a 1280px
   * candidate to paint a 218px mark, 36KB instead of 6KB.
   */
  sizes?: string;
  className?: string;
  priority?: boolean;
  /**
   * Accessible name. Pass "" when an ancestor (e.g. an aria-labelled link, or
   * a paired visible wordmark) already names the mark, to avoid a double read.
   */
  alt?: string;
};

export function Logo({
  variant = "full",
  height,
  sizes,
  className = "",
  priority = false,
  alt = "",
}: LogoProps) {
  const asset = ASSETS[variant];
  const width = Math.round((asset.width / asset.height) * height);

  return (
    <Image
      src={asset.src}
      alt={alt}
      width={width}
      height={height}
      sizes={sizes ?? `${width}px`}
      priority={priority}
      aria-hidden={alt === "" ? true : undefined}
      className={className}
    />
  );
}
